/run/initialize
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Configuration: Thickness 5 um
/BremSim/det/setFoilThickness 5 um
/run/reinitializeGeometry

# Energy 0.1 MeV
/gun/energy 0.1 MeV
/analysis/setFileName output_E_0.1MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.2 MeV
/gun/energy 0.2 MeV
/analysis/setFileName output_E_0.2MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.3 MeV
/gun/energy 0.3 MeV
/analysis/setFileName output_E_0.3MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.4 MeV
/gun/energy 0.4 MeV
/analysis/setFileName output_E_0.4MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.5 MeV
/gun/energy 0.5 MeV
/analysis/setFileName output_E_0.5MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.6 MeV
/gun/energy 0.6 MeV
/analysis/setFileName output_E_0.6MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.7 MeV
/gun/energy 0.7 MeV
/analysis/setFileName output_E_0.7MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.8 MeV
/gun/energy 0.8 MeV
/analysis/setFileName output_E_0.8MeV_T_5um.root
/run/beamOn 1000000

# Energy 0.9 MeV
/gun/energy 0.9 MeV
/analysis/setFileName output_E_0.9MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.0 MeV
/gun/energy 1.0 MeV
/analysis/setFileName output_E_1.0MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.1 MeV
/gun/energy 1.1 MeV
/analysis/setFileName output_E_1.1MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.2 MeV
/gun/energy 1.2 MeV
/analysis/setFileName output_E_1.2MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.3 MeV
/gun/energy 1.3 MeV
/analysis/setFileName output_E_1.3MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.4 MeV
/gun/energy 1.4 MeV
/analysis/setFileName output_E_1.4MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.5 MeV
/gun/energy 1.5 MeV
/analysis/setFileName output_E_1.5MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.6 MeV
/gun/energy 1.6 MeV
/analysis/setFileName output_E_1.6MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.7 MeV
/gun/energy 1.7 MeV
/analysis/setFileName output_E_1.7MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.8 MeV
/gun/energy 1.8 MeV
/analysis/setFileName output_E_1.8MeV_T_5um.root
/run/beamOn 1000000

# Energy 1.9 MeV
/gun/energy 1.9 MeV
/analysis/setFileName output_E_1.9MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.0 MeV
/gun/energy 2.0 MeV
/analysis/setFileName output_E_2.0MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.1 MeV
/gun/energy 2.1 MeV
/analysis/setFileName output_E_2.1MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.2 MeV
/gun/energy 2.2 MeV
/analysis/setFileName output_E_2.2MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.3 MeV
/gun/energy 2.3 MeV
/analysis/setFileName output_E_2.3MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.4 MeV
/gun/energy 2.4 MeV
/analysis/setFileName output_E_2.4MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.5 MeV
/gun/energy 2.5 MeV
/analysis/setFileName output_E_2.5MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.6 MeV
/gun/energy 2.6 MeV
/analysis/setFileName output_E_2.6MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.7 MeV
/gun/energy 2.7 MeV
/analysis/setFileName output_E_2.7MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.8 MeV
/gun/energy 2.8 MeV
/analysis/setFileName output_E_2.8MeV_T_5um.root
/run/beamOn 1000000

# Energy 2.9 MeV
/gun/energy 2.9 MeV
/analysis/setFileName output_E_2.9MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.0 MeV
/gun/energy 3.0 MeV
/analysis/setFileName output_E_3.0MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.1 MeV
/gun/energy 3.1 MeV
/analysis/setFileName output_E_3.1MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.2 MeV
/gun/energy 3.2 MeV
/analysis/setFileName output_E_3.2MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.3 MeV
/gun/energy 3.3 MeV
/analysis/setFileName output_E_3.3MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.4 MeV
/gun/energy 3.4 MeV
/analysis/setFileName output_E_3.4MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.5 MeV
/gun/energy 3.5 MeV
/analysis/setFileName output_E_3.5MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.6 MeV
/gun/energy 3.6 MeV
/analysis/setFileName output_E_3.6MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.7 MeV
/gun/energy 3.7 MeV
/analysis/setFileName output_E_3.7MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.8 MeV
/gun/energy 3.8 MeV
/analysis/setFileName output_E_3.8MeV_T_5um.root
/run/beamOn 1000000

# Energy 3.9 MeV
/gun/energy 3.9 MeV
/analysis/setFileName output_E_3.9MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.0 MeV
/gun/energy 4.0 MeV
/analysis/setFileName output_E_4.0MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.1 MeV
/gun/energy 4.1 MeV
/analysis/setFileName output_E_4.1MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.2 MeV
/gun/energy 4.2 MeV
/analysis/setFileName output_E_4.2MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.3 MeV
/gun/energy 4.3 MeV
/analysis/setFileName output_E_4.3MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.4 MeV
/gun/energy 4.4 MeV
/analysis/setFileName output_E_4.4MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.5 MeV
/gun/energy 4.5 MeV
/analysis/setFileName output_E_4.5MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.6 MeV
/gun/energy 4.6 MeV
/analysis/setFileName output_E_4.6MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.7 MeV
/gun/energy 4.7 MeV
/analysis/setFileName output_E_4.7MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.8 MeV
/gun/energy 4.8 MeV
/analysis/setFileName output_E_4.8MeV_T_5um.root
/run/beamOn 1000000

# Energy 4.9 MeV
/gun/energy 4.9 MeV
/analysis/setFileName output_E_4.9MeV_T_5um.root
/run/beamOn 1000000

# Energy 5.0 MeV
/gun/energy 5.0 MeV
/analysis/setFileName output_E_5.0MeV_T_5um.root
/run/beamOn 1000000

# Configuration: Thickness 50 um
/BremSim/det/setFoilThickness 50 um
/run/reinitializeGeometry

# Energy 0.1 MeV
/gun/energy 0.1 MeV
/analysis/setFileName output_E_0.1MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.2 MeV
/gun/energy 0.2 MeV
/analysis/setFileName output_E_0.2MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.3 MeV
/gun/energy 0.3 MeV
/analysis/setFileName output_E_0.3MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.4 MeV
/gun/energy 0.4 MeV
/analysis/setFileName output_E_0.4MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.5 MeV
/gun/energy 0.5 MeV
/analysis/setFileName output_E_0.5MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.6 MeV
/gun/energy 0.6 MeV
/analysis/setFileName output_E_0.6MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.7 MeV
/gun/energy 0.7 MeV
/analysis/setFileName output_E_0.7MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.8 MeV
/gun/energy 0.8 MeV
/analysis/setFileName output_E_0.8MeV_T_50um.root
/run/beamOn 1000000

# Energy 0.9 MeV
/gun/energy 0.9 MeV
/analysis/setFileName output_E_0.9MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.0 MeV
/gun/energy 1.0 MeV
/analysis/setFileName output_E_1.0MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.1 MeV
/gun/energy 1.1 MeV
/analysis/setFileName output_E_1.1MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.2 MeV
/gun/energy 1.2 MeV
/analysis/setFileName output_E_1.2MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.3 MeV
/gun/energy 1.3 MeV
/analysis/setFileName output_E_1.3MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.4 MeV
/gun/energy 1.4 MeV
/analysis/setFileName output_E_1.4MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.5 MeV
/gun/energy 1.5 MeV
/analysis/setFileName output_E_1.5MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.6 MeV
/gun/energy 1.6 MeV
/analysis/setFileName output_E_1.6MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.7 MeV
/gun/energy 1.7 MeV
/analysis/setFileName output_E_1.7MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.8 MeV
/gun/energy 1.8 MeV
/analysis/setFileName output_E_1.8MeV_T_50um.root
/run/beamOn 1000000

# Energy 1.9 MeV
/gun/energy 1.9 MeV
/analysis/setFileName output_E_1.9MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.0 MeV
/gun/energy 2.0 MeV
/analysis/setFileName output_E_2.0MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.1 MeV
/gun/energy 2.1 MeV
/analysis/setFileName output_E_2.1MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.2 MeV
/gun/energy 2.2 MeV
/analysis/setFileName output_E_2.2MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.3 MeV
/gun/energy 2.3 MeV
/analysis/setFileName output_E_2.3MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.4 MeV
/gun/energy 2.4 MeV
/analysis/setFileName output_E_2.4MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.5 MeV
/gun/energy 2.5 MeV
/analysis/setFileName output_E_2.5MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.6 MeV
/gun/energy 2.6 MeV
/analysis/setFileName output_E_2.6MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.7 MeV
/gun/energy 2.7 MeV
/analysis/setFileName output_E_2.7MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.8 MeV
/gun/energy 2.8 MeV
/analysis/setFileName output_E_2.8MeV_T_50um.root
/run/beamOn 1000000

# Energy 2.9 MeV
/gun/energy 2.9 MeV
/analysis/setFileName output_E_2.9MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.0 MeV
/gun/energy 3.0 MeV
/analysis/setFileName output_E_3.0MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.1 MeV
/gun/energy 3.1 MeV
/analysis/setFileName output_E_3.1MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.2 MeV
/gun/energy 3.2 MeV
/analysis/setFileName output_E_3.2MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.3 MeV
/gun/energy 3.3 MeV
/analysis/setFileName output_E_3.3MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.4 MeV
/gun/energy 3.4 MeV
/analysis/setFileName output_E_3.4MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.5 MeV
/gun/energy 3.5 MeV
/analysis/setFileName output_E_3.5MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.6 MeV
/gun/energy 3.6 MeV
/analysis/setFileName output_E_3.6MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.7 MeV
/gun/energy 3.7 MeV
/analysis/setFileName output_E_3.7MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.8 MeV
/gun/energy 3.8 MeV
/analysis/setFileName output_E_3.8MeV_T_50um.root
/run/beamOn 1000000

# Energy 3.9 MeV
/gun/energy 3.9 MeV
/analysis/setFileName output_E_3.9MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.0 MeV
/gun/energy 4.0 MeV
/analysis/setFileName output_E_4.0MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.1 MeV
/gun/energy 4.1 MeV
/analysis/setFileName output_E_4.1MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.2 MeV
/gun/energy 4.2 MeV
/analysis/setFileName output_E_4.2MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.3 MeV
/gun/energy 4.3 MeV
/analysis/setFileName output_E_4.3MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.4 MeV
/gun/energy 4.4 MeV
/analysis/setFileName output_E_4.4MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.5 MeV
/gun/energy 4.5 MeV
/analysis/setFileName output_E_4.5MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.6 MeV
/gun/energy 4.6 MeV
/analysis/setFileName output_E_4.6MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.7 MeV
/gun/energy 4.7 MeV
/analysis/setFileName output_E_4.7MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.8 MeV
/gun/energy 4.8 MeV
/analysis/setFileName output_E_4.8MeV_T_50um.root
/run/beamOn 1000000

# Energy 4.9 MeV
/gun/energy 4.9 MeV
/analysis/setFileName output_E_4.9MeV_T_50um.root
/run/beamOn 1000000

# Energy 5.0 MeV
/gun/energy 5.0 MeV
/analysis/setFileName output_E_5.0MeV_T_50um.root
/run/beamOn 1000000

# Configuration: Thickness 250 um
/BremSim/det/setFoilThickness 250 um
/run/reinitializeGeometry

# Energy 0.1 MeV
/gun/energy 0.1 MeV
/analysis/setFileName output_E_0.1MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.2 MeV
/gun/energy 0.2 MeV
/analysis/setFileName output_E_0.2MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.3 MeV
/gun/energy 0.3 MeV
/analysis/setFileName output_E_0.3MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.4 MeV
/gun/energy 0.4 MeV
/analysis/setFileName output_E_0.4MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.5 MeV
/gun/energy 0.5 MeV
/analysis/setFileName output_E_0.5MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.6 MeV
/gun/energy 0.6 MeV
/analysis/setFileName output_E_0.6MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.7 MeV
/gun/energy 0.7 MeV
/analysis/setFileName output_E_0.7MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.8 MeV
/gun/energy 0.8 MeV
/analysis/setFileName output_E_0.8MeV_T_250um.root
/run/beamOn 1000000

# Energy 0.9 MeV
/gun/energy 0.9 MeV
/analysis/setFileName output_E_0.9MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.0 MeV
/gun/energy 1.0 MeV
/analysis/setFileName output_E_1.0MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.1 MeV
/gun/energy 1.1 MeV
/analysis/setFileName output_E_1.1MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.2 MeV
/gun/energy 1.2 MeV
/analysis/setFileName output_E_1.2MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.3 MeV
/gun/energy 1.3 MeV
/analysis/setFileName output_E_1.3MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.4 MeV
/gun/energy 1.4 MeV
/analysis/setFileName output_E_1.4MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.5 MeV
/gun/energy 1.5 MeV
/analysis/setFileName output_E_1.5MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.6 MeV
/gun/energy 1.6 MeV
/analysis/setFileName output_E_1.6MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.7 MeV
/gun/energy 1.7 MeV
/analysis/setFileName output_E_1.7MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.8 MeV
/gun/energy 1.8 MeV
/analysis/setFileName output_E_1.8MeV_T_250um.root
/run/beamOn 1000000

# Energy 1.9 MeV
/gun/energy 1.9 MeV
/analysis/setFileName output_E_1.9MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.0 MeV
/gun/energy 2.0 MeV
/analysis/setFileName output_E_2.0MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.1 MeV
/gun/energy 2.1 MeV
/analysis/setFileName output_E_2.1MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.2 MeV
/gun/energy 2.2 MeV
/analysis/setFileName output_E_2.2MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.3 MeV
/gun/energy 2.3 MeV
/analysis/setFileName output_E_2.3MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.4 MeV
/gun/energy 2.4 MeV
/analysis/setFileName output_E_2.4MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.5 MeV
/gun/energy 2.5 MeV
/analysis/setFileName output_E_2.5MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.6 MeV
/gun/energy 2.6 MeV
/analysis/setFileName output_E_2.6MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.7 MeV
/gun/energy 2.7 MeV
/analysis/setFileName output_E_2.7MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.8 MeV
/gun/energy 2.8 MeV
/analysis/setFileName output_E_2.8MeV_T_250um.root
/run/beamOn 1000000

# Energy 2.9 MeV
/gun/energy 2.9 MeV
/analysis/setFileName output_E_2.9MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.0 MeV
/gun/energy 3.0 MeV
/analysis/setFileName output_E_3.0MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.1 MeV
/gun/energy 3.1 MeV
/analysis/setFileName output_E_3.1MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.2 MeV
/gun/energy 3.2 MeV
/analysis/setFileName output_E_3.2MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.3 MeV
/gun/energy 3.3 MeV
/analysis/setFileName output_E_3.3MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.4 MeV
/gun/energy 3.4 MeV
/analysis/setFileName output_E_3.4MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.5 MeV
/gun/energy 3.5 MeV
/analysis/setFileName output_E_3.5MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.6 MeV
/gun/energy 3.6 MeV
/analysis/setFileName output_E_3.6MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.7 MeV
/gun/energy 3.7 MeV
/analysis/setFileName output_E_3.7MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.8 MeV
/gun/energy 3.8 MeV
/analysis/setFileName output_E_3.8MeV_T_250um.root
/run/beamOn 1000000

# Energy 3.9 MeV
/gun/energy 3.9 MeV
/analysis/setFileName output_E_3.9MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.0 MeV
/gun/energy 4.0 MeV
/analysis/setFileName output_E_4.0MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.1 MeV
/gun/energy 4.1 MeV
/analysis/setFileName output_E_4.1MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.2 MeV
/gun/energy 4.2 MeV
/analysis/setFileName output_E_4.2MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.3 MeV
/gun/energy 4.3 MeV
/analysis/setFileName output_E_4.3MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.4 MeV
/gun/energy 4.4 MeV
/analysis/setFileName output_E_4.4MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.5 MeV
/gun/energy 4.5 MeV
/analysis/setFileName output_E_4.5MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.6 MeV
/gun/energy 4.6 MeV
/analysis/setFileName output_E_4.6MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.7 MeV
/gun/energy 4.7 MeV
/analysis/setFileName output_E_4.7MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.8 MeV
/gun/energy 4.8 MeV
/analysis/setFileName output_E_4.8MeV_T_250um.root
/run/beamOn 1000000

# Energy 4.9 MeV
/gun/energy 4.9 MeV
/analysis/setFileName output_E_4.9MeV_T_250um.root
/run/beamOn 1000000

# Energy 5.0 MeV
/gun/energy 5.0 MeV
/analysis/setFileName output_E_5.0MeV_T_250um.root
/run/beamOn 1000000

# Configuration: Thickness 1.0 mm
/BremSim/det/setFoilThickness 1.0 mm
/run/reinitializeGeometry

# Energy 0.1 MeV
/gun/energy 0.1 MeV
/analysis/setFileName output_E_0.1MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.2 MeV
/gun/energy 0.2 MeV
/analysis/setFileName output_E_0.2MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.3 MeV
/gun/energy 0.3 MeV
/analysis/setFileName output_E_0.3MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.4 MeV
/gun/energy 0.4 MeV
/analysis/setFileName output_E_0.4MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.5 MeV
/gun/energy 0.5 MeV
/analysis/setFileName output_E_0.5MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.6 MeV
/gun/energy 0.6 MeV
/analysis/setFileName output_E_0.6MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.7 MeV
/gun/energy 0.7 MeV
/analysis/setFileName output_E_0.7MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.8 MeV
/gun/energy 0.8 MeV
/analysis/setFileName output_E_0.8MeV_T_1mm.root
/run/beamOn 1000000

# Energy 0.9 MeV
/gun/energy 0.9 MeV
/analysis/setFileName output_E_0.9MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.0 MeV
/gun/energy 1.0 MeV
/analysis/setFileName output_E_1.0MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.1 MeV
/gun/energy 1.1 MeV
/analysis/setFileName output_E_1.1MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.2 MeV
/gun/energy 1.2 MeV
/analysis/setFileName output_E_1.2MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.3 MeV
/gun/energy 1.3 MeV
/analysis/setFileName output_E_1.3MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.4 MeV
/gun/energy 1.4 MeV
/analysis/setFileName output_E_1.4MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.5 MeV
/gun/energy 1.5 MeV
/analysis/setFileName output_E_1.5MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.6 MeV
/gun/energy 1.6 MeV
/analysis/setFileName output_E_1.6MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.7 MeV
/gun/energy 1.7 MeV
/analysis/setFileName output_E_1.7MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.8 MeV
/gun/energy 1.8 MeV
/analysis/setFileName output_E_1.8MeV_T_1mm.root
/run/beamOn 1000000

# Energy 1.9 MeV
/gun/energy 1.9 MeV
/analysis/setFileName output_E_1.9MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.0 MeV
/gun/energy 2.0 MeV
/analysis/setFileName output_E_2.0MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.1 MeV
/gun/energy 2.1 MeV
/analysis/setFileName output_E_2.1MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.2 MeV
/gun/energy 2.2 MeV
/analysis/setFileName output_E_2.2MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.3 MeV
/gun/energy 2.3 MeV
/analysis/setFileName output_E_2.3MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.4 MeV
/gun/energy 2.4 MeV
/analysis/setFileName output_E_2.4MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.5 MeV
/gun/energy 2.5 MeV
/analysis/setFileName output_E_2.5MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.6 MeV
/gun/energy 2.6 MeV
/analysis/setFileName output_E_2.6MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.7 MeV
/gun/energy 2.7 MeV
/analysis/setFileName output_E_2.7MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.8 MeV
/gun/energy 2.8 MeV
/analysis/setFileName output_E_2.8MeV_T_1mm.root
/run/beamOn 1000000

# Energy 2.9 MeV
/gun/energy 2.9 MeV
/analysis/setFileName output_E_2.9MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.0 MeV
/gun/energy 3.0 MeV
/analysis/setFileName output_E_3.0MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.1 MeV
/gun/energy 3.1 MeV
/analysis/setFileName output_E_3.1MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.2 MeV
/gun/energy 3.2 MeV
/analysis/setFileName output_E_3.2MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.3 MeV
/gun/energy 3.3 MeV
/analysis/setFileName output_E_3.3MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.4 MeV
/gun/energy 3.4 MeV
/analysis/setFileName output_E_3.4MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.5 MeV
/gun/energy 3.5 MeV
/analysis/setFileName output_E_3.5MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.6 MeV
/gun/energy 3.6 MeV
/analysis/setFileName output_E_3.6MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.7 MeV
/gun/energy 3.7 MeV
/analysis/setFileName output_E_3.7MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.8 MeV
/gun/energy 3.8 MeV
/analysis/setFileName output_E_3.8MeV_T_1mm.root
/run/beamOn 1000000

# Energy 3.9 MeV
/gun/energy 3.9 MeV
/analysis/setFileName output_E_3.9MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.0 MeV
/gun/energy 4.0 MeV
/analysis/setFileName output_E_4.0MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.1 MeV
/gun/energy 4.1 MeV
/analysis/setFileName output_E_4.1MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.2 MeV
/gun/energy 4.2 MeV
/analysis/setFileName output_E_4.2MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.3 MeV
/gun/energy 4.3 MeV
/analysis/setFileName output_E_4.3MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.4 MeV
/gun/energy 4.4 MeV
/analysis/setFileName output_E_4.4MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.5 MeV
/gun/energy 4.5 MeV
/analysis/setFileName output_E_4.5MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.6 MeV
/gun/energy 4.6 MeV
/analysis/setFileName output_E_4.6MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.7 MeV
/gun/energy 4.7 MeV
/analysis/setFileName output_E_4.7MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.8 MeV
/gun/energy 4.8 MeV
/analysis/setFileName output_E_4.8MeV_T_1mm.root
/run/beamOn 1000000

# Energy 4.9 MeV
/gun/energy 4.9 MeV
/analysis/setFileName output_E_4.9MeV_T_1mm.root
/run/beamOn 1000000

# Energy 5.0 MeV
/gun/energy 5.0 MeV
/analysis/setFileName output_E_5.0MeV_T_1mm.root
/run/beamOn 1000000

# Configuration: Thickness 2.0 mm
/BremSim/det/setFoilThickness 2.0 mm
/run/reinitializeGeometry

# Energy 0.1 MeV
/gun/energy 0.1 MeV
/analysis/setFileName output_E_0.1MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.2 MeV
/gun/energy 0.2 MeV
/analysis/setFileName output_E_0.2MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.3 MeV
/gun/energy 0.3 MeV
/analysis/setFileName output_E_0.3MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.4 MeV
/gun/energy 0.4 MeV
/analysis/setFileName output_E_0.4MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.5 MeV
/gun/energy 0.5 MeV
/analysis/setFileName output_E_0.5MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.6 MeV
/gun/energy 0.6 MeV
/analysis/setFileName output_E_0.6MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.7 MeV
/gun/energy 0.7 MeV
/analysis/setFileName output_E_0.7MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.8 MeV
/gun/energy 0.8 MeV
/analysis/setFileName output_E_0.8MeV_T_2mm.root
/run/beamOn 1000000

# Energy 0.9 MeV
/gun/energy 0.9 MeV
/analysis/setFileName output_E_0.9MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.0 MeV
/gun/energy 1.0 MeV
/analysis/setFileName output_E_1.0MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.1 MeV
/gun/energy 1.1 MeV
/analysis/setFileName output_E_1.1MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.2 MeV
/gun/energy 1.2 MeV
/analysis/setFileName output_E_1.2MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.3 MeV
/gun/energy 1.3 MeV
/analysis/setFileName output_E_1.3MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.4 MeV
/gun/energy 1.4 MeV
/analysis/setFileName output_E_1.4MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.5 MeV
/gun/energy 1.5 MeV
/analysis/setFileName output_E_1.5MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.6 MeV
/gun/energy 1.6 MeV
/analysis/setFileName output_E_1.6MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.7 MeV
/gun/energy 1.7 MeV
/analysis/setFileName output_E_1.7MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.8 MeV
/gun/energy 1.8 MeV
/analysis/setFileName output_E_1.8MeV_T_2mm.root
/run/beamOn 1000000

# Energy 1.9 MeV
/gun/energy 1.9 MeV
/analysis/setFileName output_E_1.9MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.0 MeV
/gun/energy 2.0 MeV
/analysis/setFileName output_E_2.0MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.1 MeV
/gun/energy 2.1 MeV
/analysis/setFileName output_E_2.1MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.2 MeV
/gun/energy 2.2 MeV
/analysis/setFileName output_E_2.2MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.3 MeV
/gun/energy 2.3 MeV
/analysis/setFileName output_E_2.3MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.4 MeV
/gun/energy 2.4 MeV
/analysis/setFileName output_E_2.4MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.5 MeV
/gun/energy 2.5 MeV
/analysis/setFileName output_E_2.5MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.6 MeV
/gun/energy 2.6 MeV
/analysis/setFileName output_E_2.6MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.7 MeV
/gun/energy 2.7 MeV
/analysis/setFileName output_E_2.7MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.8 MeV
/gun/energy 2.8 MeV
/analysis/setFileName output_E_2.8MeV_T_2mm.root
/run/beamOn 1000000

# Energy 2.9 MeV
/gun/energy 2.9 MeV
/analysis/setFileName output_E_2.9MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.0 MeV
/gun/energy 3.0 MeV
/analysis/setFileName output_E_3.0MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.1 MeV
/gun/energy 3.1 MeV
/analysis/setFileName output_E_3.1MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.2 MeV
/gun/energy 3.2 MeV
/analysis/setFileName output_E_3.2MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.3 MeV
/gun/energy 3.3 MeV
/analysis/setFileName output_E_3.3MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.4 MeV
/gun/energy 3.4 MeV
/analysis/setFileName output_E_3.4MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.5 MeV
/gun/energy 3.5 MeV
/analysis/setFileName output_E_3.5MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.6 MeV
/gun/energy 3.6 MeV
/analysis/setFileName output_E_3.6MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.7 MeV
/gun/energy 3.7 MeV
/analysis/setFileName output_E_3.7MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.8 MeV
/gun/energy 3.8 MeV
/analysis/setFileName output_E_3.8MeV_T_2mm.root
/run/beamOn 1000000

# Energy 3.9 MeV
/gun/energy 3.9 MeV
/analysis/setFileName output_E_3.9MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.0 MeV
/gun/energy 4.0 MeV
/analysis/setFileName output_E_4.0MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.1 MeV
/gun/energy 4.1 MeV
/analysis/setFileName output_E_4.1MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.2 MeV
/gun/energy 4.2 MeV
/analysis/setFileName output_E_4.2MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.3 MeV
/gun/energy 4.3 MeV
/analysis/setFileName output_E_4.3MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.4 MeV
/gun/energy 4.4 MeV
/analysis/setFileName output_E_4.4MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.5 MeV
/gun/energy 4.5 MeV
/analysis/setFileName output_E_4.5MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.6 MeV
/gun/energy 4.6 MeV
/analysis/setFileName output_E_4.6MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.7 MeV
/gun/energy 4.7 MeV
/analysis/setFileName output_E_4.7MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.8 MeV
/gun/energy 4.8 MeV
/analysis/setFileName output_E_4.8MeV_T_2mm.root
/run/beamOn 1000000

# Energy 4.9 MeV
/gun/energy 4.9 MeV
/analysis/setFileName output_E_4.9MeV_T_2mm.root
/run/beamOn 1000000

# Energy 5.0 MeV
/gun/energy 5.0 MeV
/analysis/setFileName output_E_5.0MeV_T_2mm.root
/run/beamOn 1000000
