# start up
/run/initialize

# vis driver
/vis/open OGL

# initialize geometry 
/vis/drawVolume

# set view angle
/vis/viewer/set/viewpointThetaPhi 70 20

# Draw particle trajectories and hits
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2

#Make the "world" box invisible
/vis/geometry/set/visbility world 0 false

# Assign colors to different particles
/vis/modeling/trajectories/create/particle-colors # "by-particle" coloring scheme
/vis/modeling/trajectories/particle-colors/set e- blue
/vis/modeling/trajectories/particle-colors/set gamma green
/vis/modeling/trajectories/particle-colors/set e+ red

# Superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

